# Generated by Django 3.1.6 on 2021-02-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_project', '0002_auto_20210213_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
